language: r

before_install:
- sudo apt-get install libv8-dev

r_packages:
- maps
- covr

r_github_packages:
- jeroenooms/V8

after_success:
- Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: DycAoDonrA+nFYb6aaxXzzmawazjMMjWrzMzVeGyysm8Pea2hWvAmFg3T+i+26IOXK6SSNZQtmW6mcB5eLIC8Gm8+SSCbZ+ETYZT21oBxER5FuX/rxQVTr18u9PMXfEGdgj4/GO1U8JLcwx/ZuzV6VhuWJGT3ONgqsqFypCvdWA=
